spring:
  main:
    banner-mode: 'off'
  datasource:
    #continue-on-error: true
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:file:~/h2_test/spring-batch;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:spring-batch;MODE=MySQL
    username: sa
    password:
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  batch:
    job:
      names: ${job.name:NONE}
