spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
#    allow-bean-definition-overriding: true

naver:
  client:
    id: ${naver.id:NONE}
    secret: ${naver.secret:NONE}
  url:
    search: https://openapi.naver.com/v1/search

search:
  es-host: localhost
  es-port: 9200
  es-index: ${es.index:restclient_test_1}


management.health.elasticsearch.enabled: false
management.health.circuitbreakers.enabled: true


logging:
  level:
    com.github.renuevo.feign.client: debug
    reactivefeign.client.log: debug


feign:
  client:
    config:
      default:
        loggerLevel: basic
        errorDecoder: com.github.renuevo.feign.config.FeignErrorDecoder
      error-retry-client:
        loggerLevel: basic
        errorDecoder: com.github.renuevo.feign.config.FeignRetryErrorDecoder


reactive:
  feign:
    client:
      config:
        default:
          # statusHandler: com.github.renuevo.feign.config.ReactiveFeignErrorDecoder
          options:
            connectTimeoutMillis: 10000
            readTimeoutMillis: 3000
          errorDecoder: com.github.renuevo.feign.config.FeignErrorDecoder   # 기존 ErrorDecoder 사용 가능 statusHandler가 있을 시 statusHandler 우선
        sample-error-reactive-retry-feign-client:
          errorDecoder: com.github.renuevo.feign.config.FeignRetryErrorDecoder
    cloud:
      enabled: false
