
spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
#    allow-bean-definition-overriding: true

naver:
  client:
    id: ${naver.id:NONE}
    secret: ${naver.secret:NONE}

search:
  es-host: localhost
  es-port: 9200
  es-index: ${es.index:restclient_test_1}


management.health.elasticsearch.enabled: false
management.health.circuitbreakers.enabled: true


logging:
  level:
    com.github.renuevo.feign.client: debug


feign:
  client:
    config:
      default:
        loggerLevel: basic
