spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
#    allow-bean-definition-overriding: true

naver:
  client:
    id: ${naver.id:NONE}
    secret: ${naver.secret:NONE}
  url:
    search: https://openapi.naver.com/v1/search

search:
  es-host: localhost
  es-port: 9200
  es-index: ${es.index:restclient_test_1}


management.health.elasticsearch.enabled: false
management.health.circuitbreakers.enabled: true


logging:
  level:
    com.github.renuevo.feign.client: debug
    reactivefeign.client.log: debug


feign:
  client:
    config:
      default:
        loggerLevel: basic

reactive:
  feign:
    logger:
      enabled: true
    ribbon:
      enabled: false
    hystrix:
      enabled: false
    loadbalancer:
      enabled: false
    circuit:
      breaker:
        enabled: false